<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>saucelab</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>37885cb4-340b-49c2-9deb-8d5cfd79616d</testSuiteGuid>
   <testCaseLink>
      <guid>1324d03d-23a8-4022-ae81-f678d66e22f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7dedb04-e647-465a-ad89-c673e090ff05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>217126a4-380c-48da-81c8-2bc5351ed2d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8741cbb5-5f2d-469d-bebc-1f3848dfb24e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/add to cart</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d8c600-1723-4bc8-97a8-71f88e989c39</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
