<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>exp_order_text</name>
   <tag></tag>
   <elementGuidId>0ceca5b2-ba6b-49dd-ab7d-0f292f7dd687</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.complete-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.complete-header</value>
   </webElementProperties>
</WebElementEntity>
