<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_cart</name>
   <tag></tag>
   <elementGuidId>6750bddd-5ada-416a-994b-3e180564d5c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.shopping_cart_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.shopping_cart_link</value>
   </webElementProperties>
</WebElementEntity>
